# Runtime stage
FROM ghcr.io/pbinitiative/zenbpm-ui:demo_20260205_latest

# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.template.conf /etc/nginx/conf.d/default.conf

ENV API_BASE_URL=http://zenbpm-1:8080

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
