# Runtime stage
FROM ghcr.io/pbinitiative/zenbpm-ui:demo_20260205_latest

# Remove default nginx config
RUN rm -rf /etc/nginx/templates/default.conf.template /etc/nginx/conf.d/default.conf

COPY nginx.template.conf /etc/nginx/templates/default.conf.template

CMD ["/bin/sh", "-c", "envsubst '${API_BASE_URL}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
